pipeline:
    name: asdjkasd
    identifier: asdjkasd
    projectIdentifier: RajathaTest
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: RajathaGitHub
                build: <+input>
    stages:
        - stage:
              name: testing
              identifier: testing
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: RajathaK8
                          namespace: rajatha-delegate-pr-env
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: testing
                                identifier: testing
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: echo test
