pipeline:
    tags: {}
    stages:
        - stage:
              name: stg1
              identifier: stg1
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: RajathaK8
                          namespace: rajatha-delegate-pr-env-may
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: step1
                                identifier: step1
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: echo nonCodebaseTest
