pipeline:
  name: rajathaimportexporttest
  identifier: rajathaimportexporttest
  projectIdentifier: RajathaTest2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: zsafdsf
        identifier: zsafdsf
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo test
