pipeline:
    name: RemotePipeline1
    identifier: RemotePipeline1
    projectIdentifier: RajathaQA
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: stg1
              identifier: stg1
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.cidelegatebuildfarm
                          namespace: harness-qa-delegate
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: step1
                                identifier: step1
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: echo run1
