pipeline:
    name: TestGitExp
    identifier: TestGitExp
    projectIdentifier: RajathaTest3
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: GitHubRajatha
                build: <+input>
    stages:
        - stage:
              name: stage
              identifier: stage
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8s
                          namespace: default
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          os: Linux
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test1
                                identifier: test1
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    shell: Sh
                                    command: <+input>
