name: Go Build
on:
  pull_request:
    branches:
      - main
      - develop

env:
  BUILD_PURPOSE: RELEASE

jobs:
  gobuild:
    if: contains(github.event.pull_request.labels.*.name, 'go') || contains(github.event.pull_request.labels.*.name, 'gojava')
    name: Go Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          go:
            - '**/**'
            - '*test.txt*'
        token: ${{ github.token }}    
      
